### ISSUE TITLE
OBJETOS NO CONVENCIONALES

### ISSUE THREAD

**Issue by benrojas01** [Irwin1985/VFPStretch#1]
Estimado Irwin,
tu aporte es maravilloso, sin embargo te cuento que tengo una clase llamada ssultimate, que contiene algunos objetos muy interesantes similares a los objetos nativos vfp, al iniciar vfpstretch,  estos objetos no sufren cambio alguno, podrías por favor asesorarme en los cambios que debo realizar al código para que funcione con dichos objetos

desde ya mil gracias

**Comment by Irwin1985** [comment]
Hola benrojas01, me alegra que te haya servido la librería. Esos controles de qué clase heredan? necesitaria tenerlos y probar para ver como puedo hacerlos compatibles.

**Comment by benrojas01** [comment]
Gracias Irwin, puedes por favor suministrarme tu correo electrónico para enviarte la información,

gracias y saludos,

**Comment by chargonzz** [comment]
Hola que tal Irwin necesito de tu asesoría y apoyo!
