### ISSUE TITLE
ComboBox ColumnWidth

### ISSUE THREAD

**Issue by IcuScc** [Irwin1985/VFPStretch#3]
Hola a todos, 
Al usar esta fantástica clase he visto que el columnwidth del combobox no se ajustaba. He añadido una solución.
He sustituido esta linea
**If m.oObject.BaseClass == 'Listbox' And !Empty(m.oObject.ColumnWidths)**
por esta otra linea
IF TYPE("m.oObject.ColumnWidths")<>"U"

Dentro del código de la clase hay dos funciones donde hay que hacer este cambio de lineas.
De momento lo veo bien.

Saludos

**Comment by Irwin1985** [comment]
Gracias @IcuScc, ya he corregido el error.

Un saludo.
