### ISSUE TITLE
Method DO minHeigth and minWidth

### ISSUE THREAD

**Issue by IcuScc** [Irwin1985/VFPStretch#4]
Hi Irwin.
I write you for inform that i changed that 2 proerties, for if you want to add the option.. only a sugeriment.

.oForm.MinHeight = .oForm.Height/4
.oForm.MinWidth  = .oForm.Width/4

now i can change the size of the screen to make smaller, and i can see it works perfect.

-----------------------
Hola Irwin.
Te escribio para informarte que cambié esas 2 propiedades, por si quieres agregar la opción... solo una sugerencia.

.oForm.AlturaMin = .oForm.Altura/4
.oForm.MinWidth = .oForm.Width/4

Ahora puedo cambiar el tamaño de la pantalla para hacerla más pequeña y puedo ver que funciona perfecto.

--------------------------

Gracias

**Comment by Irwin1985** [comment]
Hi @IcuScc,

Your idea of ​​allowing forms to be reduced up to 25% of their original size seems fantastic to me. I'm going to include the change, although you can also do it and send me the pull requests.

regards.

**Comment by IcuScc** [comment]
Hi, Irwin..

ookey.. i am glad to add the small improvements... for the moment i go to
try to mak a new pull.. because the last improvement is necessary to add
below .zoom line.
[image: imagen.png]


Missatge de 易文翰 ***@***.***> del dia dv., 19 de jul. 2024 a
les 12:51:
