### ISSUE TITLE
No se encuentra la variable QUE

### ISSUE THREAD

**Issue by IcuScc** [Irwin1985/VFPStretch#5]
Hi Irwin. 
i hope all is going well.
Using vfpStrech i have an issue in one of my forms and in one of my monitors, and i didnt found the reason yet.
the error is

Programa: STRETCHER.SAVEORIGINALSIZE
Problema: 12
Mensaje: No se encuentra la variable QUE

The line is of the error is that: =AddProperty(m.oObject, "_nOriginalWidth", m.oObject.Width)
at the begining of the function

	Function SaveOriginalSize
		Lparameters oObject
		If Pemstatus(m.oObject, 'Width', 5)
			If !Pemstatus(m.oObject, '_nOriginalWidth', 5)
				**=AddProperty(m.oObject, "_nOriginalWidth", m.oObject.Width)**
			Endif

Do you know why?
Thanks a lot.
Regards
Sergio

**Comment by Irwin1985** [comment]
Hi Sergio, that's weird. VFPStretch doesn't have any variable or identifier called "QUE". Have you reviewed your form in order to check where that value comes from? maybe it is an OLE Control or something? does it only happen with a specific form?

**Comment by IcuScc** [comment]
Hi, Irwin..
Finally i discovered what happens. I add a try ... catch block.  Yes is an OLEControl for paint the images. Its strange because only occurs with people with smaller screens.

Thansks for all.

**Comment by Irwin1985** [comment]
Hi Sergio, I'm glad you've found a solution for that particular issue. It's strange the OLE control behaves different in smaller screens, maybe it has some limitation inside.
